services:

  database:
    image: postgres:17-trixie
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: 
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  postgres_data: {}