include:
  - docker-compose.db.yaml

services:
  database_manager:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
