@WebApiAddress = http://localhost:8080

POST {{WebApiAddress}}/orders
Accept: application/json
Content-Type: application/json

{
  "firstName": "string",
  "lastName": "string",
  "totalCost": 0
}

###

GET {{WebApiAddress}}/orders/1 
Accept: application/json
