name: entityframework-migrations-sample-app

include:
  - docker-compose.db.yaml

services:
  migrations:
    build:
      context: ../..
      dockerfile: eng/docker/migrations.Dockerfile
    environment:
      - CONNECTIONSTRINGS__APPDBCONTEXT=Host=database;Database=$POSTGRES_DB;Username=$POSTGRES_USER;Password=$POSTGRES_PASSWORD
  app:
    build:
      context: ../..
      dockerfile: eng/docker/app.Dockerfile
    ports:
      - 8080:80
    environment:
      - CONNECTIONSTRINGS__APPDBCONTEXT=Host=database;Database=$POSTGRES_DB;Username=$POSTGRES_USER;Password=$POSTGRES_PASSWORD
    depends_on:
      migrations:
        condition: service_completed_successfully
      database:
        condition: service_healthy